In [ ]:
"""Exploratory data analysis of video game sales."""
# import main libraries
import pandas as pd
import plotly.express as px

-----

Featuring video games popular in North America, Japan, Europe, and beyond, 

this dataset only includes titles with a minimum of 100k in global sales.



------

In [4]:
# upload the dataset
URL = "../vgsales.csv"
df = pd.read_csv(URL)
df.sample(10)

,Name,Year,Platform,Platform_Generation,Platform_Company,NA_Sales,EU_Sales,JP_Sales,Global_Sales
7328,Shox,2002,PS2,6th,Sony,0.05,0.04,0.00,0.09
2044,Oddworld: Munch's Oddysee,2001,XB,6th,Microsoft,0.54,0.16,0.00,0.73
7083,Project: Horned Owl,1995,PS,5th,Sony,0.03,0.02,0.05,0.11
3744,Guitar Hero: Smash Hits,2009,PS3,7th,Sony,0.20,0.11,0.00,0.36
5561,Disney's Meet the Robinsons,2007,Wii,7th,Nintendo,0.17,0.00,0.00,0.19
5664,Full Auto 2: Battlelines,2006,PS3,7th,Sony,0.14,0.02,0.00,0.18
7524,The Ant Bully,2006,Wii,7th,Nintendo,0.08,0.00,0.00,0.09
3620,FlatOut,2004,PS2,6th,Sony,0.19,0.15,0.00,0.38
558,FIFA 15,2014,XOne,8th,Microsoft,0.60,1.41,0.00,2.15
3075,Walk it Out!,2010,Wii,7th,Nintendo,0.36,0.06,0.00,0.46

In [5]:
# basic info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9989 entries, 0 to 9988
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 9989 non-null   str
 1   Year                 9989 non-null   int64
 2   Platform             9989 non-null   str
 3   Platform_Generation  9989 non-null   str
 4   Platform_Company     9989 non-null   str
 5   NA_Sales             9989 non-null   float64
 6   EU_Sales             9989 non-null   float64
 7   JP_Sales             9989 non-null   float64
 8   Global_Sales         9989 non-null   float64
dtypes: float64(4), int64(1), str(4)
memory usage: 702.5 KB

In [6]:
# summary
df.describe(include="all")

,Name,Year,Platform,Platform_Generation,Platform_Company,NA_Sales,EU_Sales,JP_Sales,Global_Sales
count,9989,9989.000000,9989,9989,9989,9989.000000,9989.000000,9989.000000,9989.000000
unique,6925,NaN,15,5,4,NaN,NaN,NaN,NaN
top,Need for Speed: Most Wanted,NaN,PS2,7th,Sony,NaN,NaN,NaN,NaN
freq,7,NaN,2127,3829,4956,NaN,NaN,NaN,NaN
mean,NaN,2005.740214,NaN,NaN,NaN,0.314956,0.178918,0.068181,0.624292
std,NaN,5.639206,NaN,NaN,NaN,0.837272,0.560625,0.236912,1.628998
min,NaN,1990.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.010000
25%,NaN,2002.000000,NaN,NaN,NaN,0.020000,0.000000,0.000000,0.090000
50%,NaN,2006.000000,NaN,NaN,NaN,0.110000,0.040000,0.000000,0.230000
75%,NaN,2010.000000,NaN,NaN,NaN,0.300000,0.150000,0.030000,0.580000
max,NaN,2017.000000,NaN,NaN,NaN,41.490000,29.020000,4.700000,82.740000

In [7]:
df_long = df.melt(
    id_vars=[
        "Name",
        "Year",
        "Platform",
        "Platform_Generation",
        "Platform_Company",
        "Global_Sales",
    ],
    var_name="Country",
    value_name="Sales",
)

df_long["Country"] = df_long["Country"].apply(lambda x: x.split("_")[0])
df_long.head()

,Name,Year,Platform,Platform_Generation,Platform_Company,Global_Sales,Country,Sales
0,Wii Sports,2006,Wii,7th,Nintendo,82.74,NA,41.49
1,Mario Kart Wii,2008,Wii,7th,Nintendo,35.82,NA,15.85
2,Wii Sports Resort,2009,Wii,7th,Nintendo,33.00,NA,15.75
3,Wii Play,2006,Wii,7th,Nintendo,29.02,NA,14.03
4,New Super Mario Bros. Wii,2009,Wii,7th,Nintendo,28.62,NA,14.59

In [8]:
fig = px.bar(
    df_long,
    x="Year",
    y="Sales",
    color="Country",
    hover_name="Sales",
    barmode="group",
    title="Video Game Sales Each Year Per Country",
    labels={"Sales": "Sales (millions)"},
)
fig.show()

In [9]:
fig = px.scatter(df, x="EU_Sales", y="Global_Sales", color="Platform_Company")


fig.show()

In [10]:
fig = px.histogram(df, x="Global_Sales")


fig.show()