-----

Featuring video games popular in North America, Japan, Europe, and beyond, 

this dataset only includes titles with a minimum of 100k in global sales.



------

In [1]:
# import main libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
# upload the dataset
url = '../vgsales.csv'
df = pd.read_csv(url)
df.head()

,Name,Year,Platform,Platform_Generation,Platform_Company,NA_Sales,EU_Sales,JP_Sales,Global_Sales
0,Wii Sports,2006,Wii,7th,Nintendo,41.49,29.02,3.77,82.74
1,Mario Kart Wii,2008,Wii,7th,Nintendo,15.85,12.88,3.79,35.82
2,Wii Sports Resort,2009,Wii,7th,Nintendo,15.75,11.01,3.28,33.00
3,Wii Play,2006,Wii,7th,Nintendo,14.03,9.20,2.93,29.02
4,New Super Mario Bros. Wii,2009,Wii,7th,Nintendo,14.59,7.06,4.70,28.62

In [3]:
# basic info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9989 entries, 0 to 9988
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 9989 non-null   object
 1   Year                 9989 non-null   int64
 2   Platform             9989 non-null   object
 3   Platform_Generation  9989 non-null   object
 4   Platform_Company     9989 non-null   object
 5   NA_Sales             9989 non-null   float64
 6   EU_Sales             9989 non-null   float64
 7   JP_Sales             9989 non-null   float64
 8   Global_Sales         9989 non-null   float64
dtypes: float64(4), int64(1), object(4)
memory usage: 702.5+ KB

In [4]:
# summary 
df.describe(include='all')

,Name,Year,Platform,Platform_Generation,Platform_Company,NA_Sales,EU_Sales,JP_Sales,Global_Sales
count,9989,9989.000000,9989,9989,9989,9989.000000,9989.000000,9989.000000,9989.000000
unique,6925,NaN,15,5,4,NaN,NaN,NaN,NaN
top,NBA Jam,NaN,PS2,7th,Sony,NaN,NaN,NaN,NaN
freq,7,NaN,2127,3829,4956,NaN,NaN,NaN,NaN
mean,NaN,2005.740214,NaN,NaN,NaN,0.314956,0.178918,0.068181,0.624292
std,NaN,5.639206,NaN,NaN,NaN,0.837272,0.560625,0.236912,1.628998
min,NaN,1990.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.010000
25%,NaN,2002.000000,NaN,NaN,NaN,0.020000,0.000000,0.000000,0.090000
50%,NaN,2006.000000,NaN,NaN,NaN,0.110000,0.040000,0.000000,0.230000
75%,NaN,2010.000000,NaN,NaN,NaN,0.300000,0.150000,0.030000,0.580000
max,NaN,2017.000000,NaN,NaN,NaN,41.490000,29.020000,4.700000,82.740000

In [28]:
df_long = df.melt(id_vars=['Name', 'Year', 'Platform', 'Platform_Generation', 'Platform_Company','Global_Sales'],
                  var_name = 'Country',
                  value_name='Sales')

df_long['Country'] = df_long['Country'].apply(lambda x: x.split('_')[0])
df_long.head()

,Name,Year,Platform,Platform_Generation,Platform_Company,Global_Sales,Country,Sales
0,Wii Sports,2006,Wii,7th,Nintendo,82.74,NA,41.49
1,Mario Kart Wii,2008,Wii,7th,Nintendo,35.82,NA,15.85
2,Wii Sports Resort,2009,Wii,7th,Nintendo,33.00,NA,15.75
3,Wii Play,2006,Wii,7th,Nintendo,29.02,NA,14.03
4,New Super Mario Bros. Wii,2009,Wii,7th,Nintendo,28.62,NA,14.59

In [33]:
fig = px.bar(df_long,
             x='Year',
             y='Sales',
             color='Country',
             hover_name='Sales',
             barmode='group',
             title='Video Game Sales Each Year Per Country',
             labels={'Sales':'Sales (millions)'}
)
fig.show()

In [78]:
fig = px.scatter(df,
                 x = 'EU_Sales',
                 y = 'Global_Sales',
                 color='Platform_Company')


fig.show()

In [ ]:
fig = px.histogram(dft,
                 x = 'Year',
                 y = 'Sales',
                 color='Platform')


fig.show()

In [43]:
df_long['Platform_Company'].unique()

array(['Nintendo', 'Microsoft', 'Sony', 'Sega'], dtype=object)

In [74]:
df.query("Name=='Grand Theft Auto: San Andreas' ")

,Name,Year,Platform,Platform_Generation,Platform_Company,NA_Sales,EU_Sales,JP_Sales,Global_Sales
9,Grand Theft Auto: San Andreas,2004,PS2,6th,Sony,9.43,0.40,0.41,20.81
635,Grand Theft Auto: San Andreas,2005,XB,6th,Microsoft,1.26,0.61,0.00,1.95
6738,Grand Theft Auto: San Andreas,2008,X360,7th,Microsoft,0.08,0.03,0.00,0.12